import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,MessagesSquare,AlertTriangle,Users,SlidersHorizontal,BarChart3,Database,ShieldCheck,Search,Power,UserRoundCog,Send,RefreshCw,CheckCircle2,Clock3,Bot,ChevronRight,Menu,X,ThumbsDown,UserRound} from 'lucide-react';
import './style.css';

const API=import.meta.env.VITE_API_URL||'/api';
function useApi(key,onUnauthorized){return async (url,opts={})=>{const r=await fetch(API+url,{...opts,headers:{'Content-Type':'application/json','x-admin-key':key,...(opts.headers||{})}});if(!r.ok){if(r.status===401)onUnauthorized?.();throw new Error((await r.json().catch(()=>({}))).error||'Request failed')}return r.json()}}
const nav=[['dashboard','Dashboard',LayoutDashboard],['conversations','Conversations',MessagesSquare],['unanswered','Unanswered',AlertTriangle],['customers','Customers',Users],['leads','Sales Leads',BarChart3],['knowledge','Knowledge Base',Database],['feedback','AI Feedback',ThumbsDown],['controls','AI Control',SlidersHorizontal],['settings','Settings',ShieldCheck]];
function App(){const storedKey=localStorage.getItem('adminKey')||'';const [key,setKey]=useState(storedKey);const [authed,setAuthed]=useState(false);const [checking,setChecking]=useState(!!storedKey);const [page,setPage]=useState('dashboard');const [mobile,setMobile]=useState(false);useEffect(()=>{if(!key){setChecking(false);return}fetch(API+'/auth/check',{headers:{'x-admin-key':key}}).then(r=>setAuthed(r.ok)).catch(()=>setAuthed(false)).finally(()=>setChecking(false))},[key]);if(checking)return <Loader/>;if(!authed)return <Login onLogin={k=>{setKey(k);setAuthed(true)}}/>;const logout=()=>{localStorage.removeItem('adminKey');setKey('');setAuthed(false)};const api=useApi(key,logout);return <Shell page={page} setPage={p=>{setPage(p);setMobile(false)}} mobile={mobile} setMobile={setMobile} logout={logout}>{page==='dashboard'?<Dashboard api={api}/>:page==='conversations'?<Conversations api={api}/>:page==='unanswered'?<Unanswered api={api}/>:page==='leads'?<Leads api={api}/>:page==='feedback'?<Feedback api={api}/>:page==='controls'?<Controls api={api}/>:page==='knowledge'?<Knowledge api={api}/>:page==='customers'?<Customers api={api}/>:<Settings api={api}/>}</Shell>}
function Login({onLogin}){const [k,setK]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async()=>{setError('');setBusy(true);try{const r=await fetch(API+'/auth/check',{headers:{'x-admin-key':k}});if(!r.ok)throw new Error('Invalid admin key');localStorage.setItem('adminKey',k);onLogin(k)}catch(e){setError(e.message)}finally{setBusy(false)}};return <div className="login"><div className="loginCard"><div className="brandMark"><Bot/></div><h1>Business AI Control Center</h1><p>Admin access for your Messenger AI chatbot.</p><input type="password" placeholder="Admin key" value={k} onChange={e=>setK(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()}/><button onClick={submit} disabled={busy||!k.trim()}>{busy?'Checking...':'Sign in'}</button>{error&&<small className="error">{error}</small>}<small>Set ADMIN_KEY in the Node.js server environment.</small></div></div>}
function Shell({page,setPage,children,mobile,setMobile,logout}){return <div className="app"><aside className={mobile?'side open':'side'}><div className="brand"><div className="brandMark small"><Bot/></div><div><b>MR AI</b><span>Business Control</span></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(([id,label,I])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><I size={18}/><span>{label}</span></button>)}</nav><div className="sideBottom"><div className="status"><span className="dot"/> System online</div><button onClick={logout}>Sign out</button></div></aside><main><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div><h2>{nav.find(x=>x[0]===page)?.[1]||'Dashboard'}</h2><span className="muted">Mostafizur Rahman Shop</span></div><div className="headerRight"><span className="pill"><span className="dot"/> AI Online</span><span className="avatar">MR</span></div></header><section className="content">{children}</section></main></div>}
function Card({label,value,icon:I,sub}){return <div className="card stat"><div className="statIcon"><I size={19}/></div><div><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div></div>}
function Dashboard({api}){const [d,setD]=useState(null);useEffect(()=>{api('/overview').then(setD)},[]);if(!d)return <Loader/>;const s=d.stats;return <><div className="pageIntro"><div><h1>Good evening, Admin</h1><p>Monitor your AI customer service and sales activity.</p></div><button className="outline" onClick={()=>api('/overview').then(setD)}><RefreshCw size={16}/> Refresh</button></div><div className="grid stats"><Card label="Conversations" value={s.conversations} icon={MessagesSquare}/><Card label="Active Customers" value={s.activeCustomers} icon={Users}/><Card label="AI Responses" value={s.aiResponses} icon={Bot}/><Card label="Unanswered" value={s.unanswered} icon={AlertTriangle} sub="Needs review"/><Card label="Handoff Requests" value={s.handoffs} icon={UserRoundCog}/><Card label="Sales Leads" value={s.leads} icon={BarChart3}/></div><div className="two"><div className="panel"><div className="panelHead"><h3>System Health</h3><span className="good">All systems operational</span></div><Health api={api}/></div><div className="panel"><div className="panelHead"><h3>Recent Activity</h3><span className="muted">Live</span></div><Events events={d.recentEvents}/></div></div></>}
function Health({api}){const [h,setH]=useState(null);useEffect(()=>{api('/health').then(setH)},[]);if(!h)return <Loader/>;return <div className="health">{[['AI Model','ai'],['Google Sheets','googleSheets'],['Facebook Messenger','facebook'],['Storage','storage']].map(([n,k])=><div key={k}><span>{n}</span><b><span className="dot"/> {h[k]}</b></div>)}</div>}
function Events({events=[]}){return <div className="events">{events.length?events.map(e=><div className="event" key={e.id}><div className="eventIcon"><Clock3 size={15}/></div><div><b>{e.type.replaceAll('_',' ')}</b><small>{new Date(e.time).toLocaleString()}</small></div></div>):<Empty text="No activity yet"/>}</div>}
function Conversations({api}){const [cs,setCs]=useState([]),[sel,setSel]=useState(null),[q,setQ]=useState('');const load=()=>api('/conversations').then(data=>{setCs(data);setSel(current=>current?data.find(c=>c.id===current.id)||null:current);return data});useEffect(()=>{load();const es=new EventSource(API+'/events/stream');es.onmessage=()=>load();return()=>es.close()},[]);const filtered=cs.filter(c=>(c.customerName+' '+c.customerId).toLowerCase().includes(q.toLowerCase()));return <div className="convLayout"><div className="panel convList"><div className="toolbar"><div className="search"><Search size={16}/><input placeholder="Search customer..." value={q} onChange={e=>setQ(e.target.value)}/></div></div>{filtered.map(c=><button className={sel?.id===c.id?'conv active':''||'conv'} key={c.id} onClick={()=>setSel(c)}><div className="avatar">{c.customerName[0]}</div><div className="convText"><b>{c.customerName}</b><span>{c.messages.at(-1)?.content||'No messages'}</span></div><Status s={c.status}/></button>)}</div><div className="panel thread">{sel?<Thread c={sel} api={api} refresh={load}/>:<Empty text="Select a conversation"/>}</div></div>}
function Thread({c,api,refresh}){const [text,setText]=useState('');const mode=m=>api('/conversations/'+c.id+'/mode',{method:'POST',body:JSON.stringify({mode:m})}).then(refresh);const send=()=>{if(!text.trim())return;api('/conversations/'+c.id+'/reply',{method:'POST',body:JSON.stringify({text})}).then(()=>{setText('');refresh()})};return <><div className="threadHead"><div><h3>{c.customerName}</h3><span className="muted">{c.customerId}</span></div><div className="actions"><Status s={c.status}/>{c.status!=='HUMAN_ACTIVE'?<button className="danger" onClick={()=>mode('HUMAN_ACTIVE')}><UserRoundCog size={15}/> Take over</button>:<button className="outline" onClick={()=>mode('AI_ACTIVE')}><Bot size={15}/> Return to AI</button>}</div></div><div className="messages">{c.messages.map(m=><div className={'msg '+m.role} key={m.id}><div className="msgRole">{m.role==='user'?c.customerName:m.role==='assistant'?'AI':'Human'}</div><div className="bubble">{m.content}</div><small>{new Date(m.time).toLocaleString()}</small></div>)}</div>{c.status==='HUMAN_ACTIVE'&&<div className="composer"><input placeholder="Reply as human agent..." value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()}/><button onClick={send}><Send size={17}/></button></div>}</>}
function Unanswered({api}){const [xs,setXs]=useState([]);const load=()=>api('/unanswered').then(setXs);useEffect(load,[]);return <div className="panel"><div className="panelHead"><div><h3>Unanswered questions</h3><p className="muted">Questions the AI could not confidently answer.</p></div><button className="outline" onClick={load}><RefreshCw size={16}/> Refresh</button></div><Table headers={['Question','Customer','Confidence','Status','Action']} rows={xs.map(x=>[<b>{x.question}</b>,x.customerName,Math.round(x.confidence*100)+'%',<Status s={x.status}/>,<select value={x.status} onChange={e=>api('/unanswered/'+x.id+'/status',{method:'POST',body:JSON.stringify({status:e.target.value})}).then(load)}><option>NEW</option><option>REVIEWED</option><option>ANSWERED</option><option>IGNORED</option></select>])}/></div>}
function Leads({api}){const [xs,setXs]=useState([]);useEffect(()=>{api('/leads').then(setXs)},[]);return <div className="panel"><div className="panelHead"><div><h3>Sales leads</h3><p className="muted">Buying-intent customers collected by the chatbot.</p></div></div><Table headers={['Customer','Product','Budget','Status','Created']} rows={xs.map(x=>[x.customerName||'Unknown',x.product||'—',x.budget||'—',<Status s={x.status}/>,new Date(x.createdAt).toLocaleString()])}/></div>}
function Feedback({api}){const [xs,setXs]=useState([]);useEffect(()=>{api('/feedback').then(setXs)},[]);return <div className="panel"><div className="panelHead"><div><h3>AI feedback</h3><p className="muted">Review helpful and incorrect responses.</p></div></div><Table headers={['Question','AI Answer','Feedback','Date']} rows={xs.map(x=>[x.question||'—',x.answer||'—',x.type||'—',new Date(x.createdAt).toLocaleString()])}/></div>}
function Controls({api}){const [s,setS]=useState(null);useEffect(()=>{api('/settings').then(setS)},[]);if(!s)return <Loader/>;const toggle=(k)=>{const n={...s,[k]:!s[k]};setS(n);api('/settings',{method:'PUT',body:JSON.stringify(n)})};return <div className="settingsGrid"><div className="panel"><div className="panelHead"><div><h3>AI Control Center</h3><p className="muted">Changes apply to the backend configuration.</p></div></div>{[['aiEnabled','AI responses'],['memoryEnabled','Conversation memory'],['faqSearchEnabled','Google Sheets FAQ search'],['salesAssistantEnabled','Sales assistant'],['banglaSupport','Bangla / Banglish support'],['humanHandoffEnabled','Human handoff']].map(([k,n])=><div className="settingRow" key={k}><div><b>{n}</b><span>{s[k]?'Enabled':'Disabled'}</span></div><button className={s[k]?'switch on':'switch'} onClick={()=>toggle(k)}><i/></button></div>)}</div><div className="panel"><h3>Search confidence</h3><p className="muted">Minimum relevance score before the AI treats a knowledge result as reliable.</p><input className="range" type="range" min="0.5" max="0.98" step="0.01" value={s.faqConfidence} onChange={e=>{const n={...s,faqConfidence:+e.target.value};setS(n)}} onMouseUp={()=>api('/settings',{method:'PUT',body:JSON.stringify(s)})}/><div className="rangeValue">{Math.round(s.faqConfidence*100)}%</div><div className="note"><ShieldCheck size={17}/> Never use this setting to make the AI invent missing business data.</div></div></div>}
function Knowledge({api}){return <div className="grid twoCards"><div className="panel source"><div className="sourceIcon"><Database/></div><div><h3>Ecommerce_Customer_FAQ_Google_Sheets</h3><p className="muted">FAQ / business knowledge source</p><span className="good"><span className="dot"/> Connected</span></div><button className="outline" onClick={()=>api('/health').then(()=>alert('Health check completed.'))}>Check</button></div><div className="panel source"><div className="sourceIcon"><ShieldCheck/></div><div><h3>Business profile</h3><p className="muted">মোস্তাফিজুর রহমান শপ · গাইবান্ধা, বাংলাদেশ</p><span>01580913655</span></div></div></div>}
function Customers({api}){const [cs,setCs]=useState([]);useEffect(()=>{api('/conversations').then(setCs)},[]);return <div className="panel"><div className="panelHead"><h3>Customers</h3></div><Table headers={['Customer','Customer ID','Conversations','Last activity','Status']} rows={cs.map(c=>[c.customerName,c.customerId,1,new Date(c.lastActivity).toLocaleString(),<Status s={c.status}/>])}/></div>}
function Settings({api}){return <div className="panel"><h3>System settings</h3><p className="muted">This dashboard uses a backend admin key. For production, replace the simple key with your existing secure authentication/authorization system.</p><div className="note"><ShieldCheck size={17}/> API keys, Google credentials and Facebook tokens should remain server-side.</div></div>}
function Table({headers,rows}){return rows.length?<div className="tableWrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>:<Empty text="Nothing to show"/>}
function Status({s}){const map={AI_ACTIVE:'AI Active',HUMAN_ACTIVE:'Human',HANDOFF_REQUIRED:'Handoff',CLOSED:'Closed',NEW:'New',REVIEWED:'Reviewed',ANSWERED:'Answered',IGNORED:'Ignored'};return <span className={'statusBadge '+String(s).toLowerCase()}>{map[s]||s}</span>}
function Empty({text}){return <div className="empty"><div><Database size={22}/></div><b>{text}</b><span className="muted">Data will appear here as your chatbot sends events.</span></div>}
function Loader(){return <div className="loading"><RefreshCw className="spin"/> Loading...</div>}

createRoot(document.getElementById('root')).render(<App/>);
